CREATE TABLE [dbo].[BBBEWDUP] (
    [ID_BEW_DUP]  INT          NOT NULL,
    [SCF_BEW_DUP] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_BBBEWDUP] PRIMARY KEY CLUSTERED ([ID_BEW_DUP] ASC) WITH (FILLFACTOR = 70)
);

