CREATE TABLE [dbo].[BBOGVSTA] (
    [ID_REG] INT NOT NULL,
    [ID_STA] INT NOT NULL,
    CONSTRAINT [PK_BBOGVSTA] PRIMARY KEY CLUSTERED ([ID_REG] ASC, [ID_STA] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_BBOGVSTA_BBOGVTSP] FOREIGN KEY ([ID_REG]) REFERENCES [dbo].[BBOGVTSP] ([ID_REG]),
    CONSTRAINT [FK_BBOGVSTA_BBSTA] FOREIGN KEY ([ID_STA]) REFERENCES [dbo].[BBSTA] ([ID_STA])
);


GO
CREATE NONCLUSTERED INDEX [I_BBOGVSTA_01]
    ON [dbo].[BBOGVSTA]([ID_STA] ASC) WITH (FILLFACTOR = 70);

