CREATE TABLE [dbo].[BBVASTOGV] (
    [ID_VAST_OGV]  INT          IDENTITY (1, 1) NOT NULL,
    [SCF_VAST_OGV] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_BBVASTOGV] PRIMARY KEY CLUSTERED ([ID_VAST_OGV] ASC) WITH (FILLFACTOR = 70)
);

