CREATE TABLE [dbo].[BVLGRPR] (
    [ID_GR]   CHAR (50) NOT NULL,
    [ID_TOEP] CHAR (50) NOT NULL,
    [ID_PRFL] CHAR (50) NOT NULL,
    CONSTRAINT [BVLGRPR_PK] PRIMARY KEY CLUSTERED ([ID_GR] ASC, [ID_TOEP] ASC, [ID_PRFL] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [BVLGR_BVLGRPR_FK1] FOREIGN KEY ([ID_GR]) REFERENCES [dbo].[BVLGR] ([ID_GR]),
    CONSTRAINT [BVLPRFL_BVLGRPR_FK1] FOREIGN KEY ([ID_TOEP], [ID_PRFL]) REFERENCES [dbo].[BVLPRFL] ([ID_TOEP], [ID_PRFL])
);


GO
CREATE NONCLUSTERED INDEX [I_BVLGRPR_01]
    ON [dbo].[BVLGRPR]([ID_TOEP] ASC, [ID_PRFL] ASC) WITH (FILLFACTOR = 70);

