CREATE TABLE [dbo].[BVLINDPR] (
    [ID_IND]  CHAR (50) NOT NULL,
    [ID_TOEP] CHAR (50) NOT NULL,
    [ID_PRFL] CHAR (50) NOT NULL,
    CONSTRAINT [BVLINDPR_PK] PRIMARY KEY CLUSTERED ([ID_IND] ASC, [ID_TOEP] ASC, [ID_PRFL] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [BVLIND_BVLINDPR_FK1] FOREIGN KEY ([ID_IND]) REFERENCES [dbo].[BVLIND] ([ID_IND]),
    CONSTRAINT [BVLPRFL_BVLINDPR_FK1] FOREIGN KEY ([ID_TOEP], [ID_PRFL]) REFERENCES [dbo].[BVLPRFL] ([ID_TOEP], [ID_PRFL])
);


GO
CREATE NONCLUSTERED INDEX [I_BVLINDPR_01]
    ON [dbo].[BVLINDPR]([ID_TOEP] ASC, [ID_PRFL] ASC) WITH (FILLFACTOR = 70);

