CREATE TABLE [dbo].[BVLPGGD] (
    [ID_TOEP_PRFL] CHAR (50) NOT NULL,
    [ID_PRFL]      CHAR (50) NOT NULL,
    [ID_TOEP_GGD]  CHAR (50) NOT NULL,
    [ID_GGD]       CHAR (50) NOT NULL,
    CONSTRAINT [BVLPGGD_PK] PRIMARY KEY CLUSTERED ([ID_GGD] ASC, [ID_PRFL] ASC, [ID_TOEP_GGD] ASC, [ID_TOEP_PRFL] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [BVLGGD_BVLPGGD_FK1] FOREIGN KEY ([ID_TOEP_GGD], [ID_GGD]) REFERENCES [dbo].[BVLGGD] ([ID_TOEP], [ID_GGD]),
    CONSTRAINT [BVLPRFL_BVLPGGD_FK1] FOREIGN KEY ([ID_TOEP_PRFL], [ID_PRFL]) REFERENCES [dbo].[BVLPRFL] ([ID_TOEP], [ID_PRFL])
);


GO
CREATE NONCLUSTERED INDEX [I_BVLPGGD_02]
    ON [dbo].[BVLPGGD]([ID_TOEP_PRFL] ASC, [ID_PRFL] ASC) WITH (FILLFACTOR = 70);


GO
CREATE NONCLUSTERED INDEX [I_BVLPGGD_01]
    ON [dbo].[BVLPGGD]([ID_TOEP_GGD] ASC, [ID_GGD] ASC) WITH (FILLFACTOR = 70);

