CREATE TABLE [dbo].[BVLPTKWR] (
    [ID_TOEP_PRFL]  CHAR (50) NOT NULL,
    [ID_PRFL]       CHAR (50) NOT NULL,
    [ID_TOEP_TK_WR] CHAR (50) NOT NULL,
    [ID_WR]         CHAR (50) NOT NULL,
    [ID_TK]         CHAR (50) NOT NULL,
    CONSTRAINT [PK_BVLPTKWR] PRIMARY KEY CLUSTERED ([ID_TOEP_PRFL] ASC, [ID_PRFL] ASC, [ID_TOEP_TK_WR] ASC, [ID_WR] ASC, [ID_TK] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_BVLPTKWR_BVLPRFL] FOREIGN KEY ([ID_TOEP_PRFL], [ID_PRFL]) REFERENCES [dbo].[BVLPRFL] ([ID_TOEP], [ID_PRFL]),
    CONSTRAINT [FK_BVLPTKWR_BVLTKWR] FOREIGN KEY ([ID_TOEP_TK_WR], [ID_WR], [ID_TK]) REFERENCES [dbo].[BVLTKWR] ([ID_TOEP], [ID_WR], [ID_TK])
);


GO
CREATE NONCLUSTERED INDEX [I_BVLPTKWR_01]
    ON [dbo].[BVLPTKWR]([ID_TOEP_TK_WR] ASC, [ID_WR] ASC, [ID_TK] ASC) WITH (FILLFACTOR = 70);

