'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("TDSRegBew"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class TDSRegBew
    Inherits Global.System.Data.DataSet
    
    Private tableBBBEWREG As BBBEWREGDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("BBBEWREG")) Is Nothing) Then
                MyBase.Tables.Add(New BBBEWREGDataTable(ds.Tables("BBBEWREG")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property BBBEWREG() As BBBEWREGDataTable
        Get
            Return Me.tableBBBEWREG
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As TDSRegBew = CType(MyBase.Clone,TDSRegBew)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("BBBEWREG")) Is Nothing) Then
                MyBase.Tables.Add(New BBBEWREGDataTable(ds.Tables("BBBEWREG")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableBBBEWREG = CType(MyBase.Tables("BBBEWREG"),BBBEWREGDataTable)
        If (initTable = true) Then
            If (Not (Me.tableBBBEWREG) Is Nothing) Then
                Me.tableBBBEWREG.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "TDSRegBew"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/TDSRegBew.xsd"
        Me.Locale = New Global.System.Globalization.CultureInfo("en-US")
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableBBBEWREG = New BBBEWREGDataTable()
        MyBase.Tables.Add(Me.tableBBBEWREG)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializeBBBEWREG() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As TDSRegBew = New TDSRegBew()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub BBBEWREGRowChangeEventHandler(ByVal sender As Object, ByVal e As BBBEWREGRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class BBBEWREGDataTable
        Inherits Global.System.Data.TypedTableBase(Of BBBEWREGRow)
        
        Private columnID_REG As Global.System.Data.DataColumn
        
        Private columnID_TY_REG As Global.System.Data.DataColumn
        
        Private columnNM_IND As Global.System.Data.DataColumn
        
        Private columnVNM_IND As Global.System.Data.DataColumn
        
        Private columnSCF_PLG_IND As Global.System.Data.DataColumn
        
        Private columnSCF_TY_REG As Global.System.Data.DataColumn
        
        Private columnVLG_REG_JR_BPL As Global.System.Data.DataColumn
        
        Private columnJR_REG As Global.System.Data.DataColumn
        
        Private columnTMS_OPS_REG As Global.System.Data.DataColumn
        
        Private columnTMS_INC As Global.System.Data.DataColumn
        
        Private columnPLA_INC As Global.System.Data.DataColumn
        
        Private columnDT_VZ_RAP_NW As Global.System.Data.DataColumn
        
        Private columnDT_OK As Global.System.Data.DataColumn
        
        Private columnDT_VZ_BST As Global.System.Data.DataColumn
        
        Private columnOPM_OPS As Global.System.Data.DataColumn
        
        Private columnOPM_CHEF_PO As Global.System.Data.DataColumn
        
        Private columnOPM_HFD_BRW As Global.System.Data.DataColumn
        
        Private columnID_OPS As Global.System.Data.DataColumn
        
        Private columnDT_OPS_RAP_INTV As Global.System.Data.DataColumn
        
        Private columnSCF_REG As Global.System.Data.DataColumn
        
        Private columnSAP_SUPPLIER_ID As Global.System.Data.DataColumn
        
        Private columnDT_CHIP As Global.System.Data.DataColumn
        
        Private columnOPM_CHIP As Global.System.Data.DataColumn
        
        Private columnCHIP_YN As Global.System.Data.DataColumn
        
        Private columnVeraReference As Global.System.Data.DataColumn
        
        Private columnVerslagContractantYN As Global.System.Data.DataColumn
        
        Private columnTMS_IKP_SENDMAIL As Global.System.Data.DataColumn
        
        Private columnDateInvalid As Global.System.Data.DataColumn
        
        Private columnUserInvalid As Global.System.Data.DataColumn
        
        Private columnRemarkInvalid As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "BBBEWREG"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ID_REGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnID_REG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ID_TY_REGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnID_TY_REG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NM_INDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNM_IND
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VNM_INDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVNM_IND
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SCF_PLG_INDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSCF_PLG_IND
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SCF_TY_REGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSCF_TY_REG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VLG_REG_JR_BPLColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVLG_REG_JR_BPL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property JR_REGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnJR_REG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TMS_OPS_REGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTMS_OPS_REG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TMS_INCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTMS_INC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PLA_INCColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPLA_INC
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DT_VZ_RAP_NWColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDT_VZ_RAP_NW
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DT_OKColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDT_OK
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DT_VZ_BSTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDT_VZ_BST
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property OPM_OPSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOPM_OPS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property OPM_CHEF_POColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOPM_CHEF_PO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property OPM_HFD_BRWColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOPM_HFD_BRW
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ID_OPSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnID_OPS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DT_OPS_RAP_INTVColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDT_OPS_RAP_INTV
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SCF_REGColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSCF_REG
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SAP_SUPPLIER_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSAP_SUPPLIER_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DT_CHIPColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDT_CHIP
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property OPM_CHIPColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOPM_CHIP
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CHIP_YNColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCHIP_YN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VeraReferenceColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVeraReference
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VerslagContractantYNColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVerslagContractantYN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TMS_IKP_SENDMAILColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTMS_IKP_SENDMAIL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DateInvalidColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDateInvalid
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property UserInvalidColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUserInvalid
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RemarkInvalidColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRemarkInvalid
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As BBBEWREGRow
            Get
                Return CType(Me.Rows(index),BBBEWREGRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event BBBEWREGRowChanging As BBBEWREGRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event BBBEWREGRowChanged As BBBEWREGRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event BBBEWREGRowDeleting As BBBEWREGRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event BBBEWREGRowDeleted As BBBEWREGRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddBBBEWREGRow(ByVal row As BBBEWREGRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddBBBEWREGRow( _
                    ByVal ID_REG As Integer,  _
                    ByVal ID_TY_REG As Integer,  _
                    ByVal NM_IND As String,  _
                    ByVal VNM_IND As String,  _
                    ByVal SCF_PLG_IND As String,  _
                    ByVal SCF_TY_REG As String,  _
                    ByVal VLG_REG_JR_BPL As Integer,  _
                    ByVal JR_REG As Integer,  _
                    ByVal TMS_OPS_REG As Date,  _
                    ByVal TMS_INC As Date,  _
                    ByVal PLA_INC As String,  _
                    ByVal DT_VZ_RAP_NW As Date,  _
                    ByVal DT_OK As Date,  _
                    ByVal DT_VZ_BST As Date,  _
                    ByVal OPM_OPS As String,  _
                    ByVal OPM_CHEF_PO As String,  _
                    ByVal OPM_HFD_BRW As String,  _
                    ByVal ID_OPS As Integer,  _
                    ByVal DT_OPS_RAP_INTV As Date,  _
                    ByVal SCF_REG As String,  _
                    ByVal SAP_SUPPLIER_ID As String,  _
                    ByVal DT_CHIP As Date,  _
                    ByVal OPM_CHIP As String,  _
                    ByVal CHIP_YN As Boolean,  _
                    ByVal VeraReference As String,  _
                    ByVal VerslagContractantYN As Boolean,  _
                    ByVal TMS_IKP_SENDMAIL As Date,  _
                    ByVal DateInvalid As Date,  _
                    ByVal UserInvalid As String,  _
                    ByVal RemarkInvalid As String) As BBBEWREGRow
            Dim rowBBBEWREGRow As BBBEWREGRow = CType(Me.NewRow,BBBEWREGRow)
            Dim columnValuesArray() As Object = New Object() {ID_REG, ID_TY_REG, NM_IND, VNM_IND, SCF_PLG_IND, SCF_TY_REG, VLG_REG_JR_BPL, JR_REG, TMS_OPS_REG, TMS_INC, PLA_INC, DT_VZ_RAP_NW, DT_OK, DT_VZ_BST, OPM_OPS, OPM_CHEF_PO, OPM_HFD_BRW, ID_OPS, DT_OPS_RAP_INTV, SCF_REG, SAP_SUPPLIER_ID, DT_CHIP, OPM_CHIP, CHIP_YN, VeraReference, VerslagContractantYN, TMS_IKP_SENDMAIL, DateInvalid, UserInvalid, RemarkInvalid}
            rowBBBEWREGRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowBBBEWREGRow)
            Return rowBBBEWREGRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function FindByID_REG(ByVal ID_REG As Integer) As BBBEWREGRow
            Return CType(Me.Rows.Find(New Object() {ID_REG}),BBBEWREGRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As BBBEWREGDataTable = CType(MyBase.Clone,BBBEWREGDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New BBBEWREGDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnID_REG = MyBase.Columns("ID_REG")
            Me.columnID_TY_REG = MyBase.Columns("ID_TY_REG")
            Me.columnNM_IND = MyBase.Columns("NM_IND")
            Me.columnVNM_IND = MyBase.Columns("VNM_IND")
            Me.columnSCF_PLG_IND = MyBase.Columns("SCF_PLG_IND")
            Me.columnSCF_TY_REG = MyBase.Columns("SCF_TY_REG")
            Me.columnVLG_REG_JR_BPL = MyBase.Columns("VLG_REG_JR_BPL")
            Me.columnJR_REG = MyBase.Columns("JR_REG")
            Me.columnTMS_OPS_REG = MyBase.Columns("TMS_OPS_REG")
            Me.columnTMS_INC = MyBase.Columns("TMS_INC")
            Me.columnPLA_INC = MyBase.Columns("PLA_INC")
            Me.columnDT_VZ_RAP_NW = MyBase.Columns("DT_VZ_RAP_NW")
            Me.columnDT_OK = MyBase.Columns("DT_OK")
            Me.columnDT_VZ_BST = MyBase.Columns("DT_VZ_BST")
            Me.columnOPM_OPS = MyBase.Columns("OPM_OPS")
            Me.columnOPM_CHEF_PO = MyBase.Columns("OPM_CHEF_PO")
            Me.columnOPM_HFD_BRW = MyBase.Columns("OPM_HFD_BRW")
            Me.columnID_OPS = MyBase.Columns("ID_OPS")
            Me.columnDT_OPS_RAP_INTV = MyBase.Columns("DT_OPS_RAP_INTV")
            Me.columnSCF_REG = MyBase.Columns("SCF_REG")
            Me.columnSAP_SUPPLIER_ID = MyBase.Columns("SAP_SUPPLIER_ID")
            Me.columnDT_CHIP = MyBase.Columns("DT_CHIP")
            Me.columnOPM_CHIP = MyBase.Columns("OPM_CHIP")
            Me.columnCHIP_YN = MyBase.Columns("CHIP_YN")
            Me.columnVeraReference = MyBase.Columns("VeraReference")
            Me.columnVerslagContractantYN = MyBase.Columns("VerslagContractantYN")
            Me.columnTMS_IKP_SENDMAIL = MyBase.Columns("TMS_IKP_SENDMAIL")
            Me.columnDateInvalid = MyBase.Columns("DateInvalid")
            Me.columnUserInvalid = MyBase.Columns("UserInvalid")
            Me.columnRemarkInvalid = MyBase.Columns("RemarkInvalid")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnID_REG = New Global.System.Data.DataColumn("ID_REG", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID_REG)
            Me.columnID_TY_REG = New Global.System.Data.DataColumn("ID_TY_REG", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID_TY_REG)
            Me.columnNM_IND = New Global.System.Data.DataColumn("NM_IND", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNM_IND)
            Me.columnVNM_IND = New Global.System.Data.DataColumn("VNM_IND", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVNM_IND)
            Me.columnSCF_PLG_IND = New Global.System.Data.DataColumn("SCF_PLG_IND", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSCF_PLG_IND)
            Me.columnSCF_TY_REG = New Global.System.Data.DataColumn("SCF_TY_REG", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSCF_TY_REG)
            Me.columnVLG_REG_JR_BPL = New Global.System.Data.DataColumn("VLG_REG_JR_BPL", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVLG_REG_JR_BPL)
            Me.columnJR_REG = New Global.System.Data.DataColumn("JR_REG", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnJR_REG)
            Me.columnTMS_OPS_REG = New Global.System.Data.DataColumn("TMS_OPS_REG", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTMS_OPS_REG)
            Me.columnTMS_INC = New Global.System.Data.DataColumn("TMS_INC", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTMS_INC)
            Me.columnPLA_INC = New Global.System.Data.DataColumn("PLA_INC", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPLA_INC)
            Me.columnDT_VZ_RAP_NW = New Global.System.Data.DataColumn("DT_VZ_RAP_NW", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDT_VZ_RAP_NW)
            Me.columnDT_OK = New Global.System.Data.DataColumn("DT_OK", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDT_OK)
            Me.columnDT_VZ_BST = New Global.System.Data.DataColumn("DT_VZ_BST", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDT_VZ_BST)
            Me.columnOPM_OPS = New Global.System.Data.DataColumn("OPM_OPS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOPM_OPS)
            Me.columnOPM_CHEF_PO = New Global.System.Data.DataColumn("OPM_CHEF_PO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOPM_CHEF_PO)
            Me.columnOPM_HFD_BRW = New Global.System.Data.DataColumn("OPM_HFD_BRW", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOPM_HFD_BRW)
            Me.columnID_OPS = New Global.System.Data.DataColumn("ID_OPS", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnID_OPS)
            Me.columnDT_OPS_RAP_INTV = New Global.System.Data.DataColumn("DT_OPS_RAP_INTV", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDT_OPS_RAP_INTV)
            Me.columnSCF_REG = New Global.System.Data.DataColumn("SCF_REG", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSCF_REG)
            Me.columnSAP_SUPPLIER_ID = New Global.System.Data.DataColumn("SAP_SUPPLIER_ID", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSAP_SUPPLIER_ID)
            Me.columnDT_CHIP = New Global.System.Data.DataColumn("DT_CHIP", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDT_CHIP)
            Me.columnOPM_CHIP = New Global.System.Data.DataColumn("OPM_CHIP", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOPM_CHIP)
            Me.columnCHIP_YN = New Global.System.Data.DataColumn("CHIP_YN", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCHIP_YN)
            Me.columnVeraReference = New Global.System.Data.DataColumn("VeraReference", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVeraReference)
            Me.columnVerslagContractantYN = New Global.System.Data.DataColumn("VerslagContractantYN", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVerslagContractantYN)
            Me.columnTMS_IKP_SENDMAIL = New Global.System.Data.DataColumn("TMS_IKP_SENDMAIL", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTMS_IKP_SENDMAIL)
            Me.columnDateInvalid = New Global.System.Data.DataColumn("DateInvalid", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDateInvalid)
            Me.columnUserInvalid = New Global.System.Data.DataColumn("UserInvalid", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUserInvalid)
            Me.columnRemarkInvalid = New Global.System.Data.DataColumn("RemarkInvalid", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRemarkInvalid)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnID_REG}, true))
            Me.columnID_REG.AllowDBNull = false
            Me.columnID_REG.Unique = true
            Me.columnNM_IND.MaxLength = 50
            Me.columnVNM_IND.MaxLength = 50
            Me.columnSCF_PLG_IND.MaxLength = 50
            Me.columnSCF_TY_REG.MaxLength = 30
            Me.columnJR_REG.ReadOnly = true
            Me.columnPLA_INC.MaxLength = 200
            Me.columnOPM_OPS.MaxLength = 100
            Me.columnOPM_CHEF_PO.MaxLength = 100
            Me.columnOPM_HFD_BRW.MaxLength = 100
            Me.columnSCF_REG.MaxLength = 250
            Me.columnSAP_SUPPLIER_ID.MaxLength = 30
            Me.columnOPM_CHIP.MaxLength = 100
            Me.columnCHIP_YN.ReadOnly = true
            Me.columnVerslagContractantYN.DefaultValue = CType(false,Boolean)
            Me.columnUserInvalid.MaxLength = 30
            Me.columnRemarkInvalid.MaxLength = 200
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewBBBEWREGRow() As BBBEWREGRow
            Return CType(Me.NewRow,BBBEWREGRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New BBBEWREGRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(BBBEWREGRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.BBBEWREGRowChangedEvent) Is Nothing) Then
                RaiseEvent BBBEWREGRowChanged(Me, New BBBEWREGRowChangeEvent(CType(e.Row,BBBEWREGRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.BBBEWREGRowChangingEvent) Is Nothing) Then
                RaiseEvent BBBEWREGRowChanging(Me, New BBBEWREGRowChangeEvent(CType(e.Row,BBBEWREGRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.BBBEWREGRowDeletedEvent) Is Nothing) Then
                RaiseEvent BBBEWREGRowDeleted(Me, New BBBEWREGRowChangeEvent(CType(e.Row,BBBEWREGRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.BBBEWREGRowDeletingEvent) Is Nothing) Then
                RaiseEvent BBBEWREGRowDeleting(Me, New BBBEWREGRowChangeEvent(CType(e.Row,BBBEWREGRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemoveBBBEWREGRow(ByVal row As BBBEWREGRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As TDSRegBew = New TDSRegBew()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "BBBEWREGDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class BBBEWREGRow
        Inherits Global.System.Data.DataRow
        
        Private tableBBBEWREG As BBBEWREGDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableBBBEWREG = CType(Me.Table,BBBEWREGDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ID_REG() As Integer
            Get
                Return CType(Me(Me.tableBBBEWREG.ID_REGColumn),Integer)
            End Get
            Set
                Me(Me.tableBBBEWREG.ID_REGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ID_TY_REG() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.ID_TY_REGColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ID_TY_REG' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.ID_TY_REGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NM_IND() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.NM_INDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NM_IND' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.NM_INDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VNM_IND() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.VNM_INDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'VNM_IND' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.VNM_INDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SCF_PLG_IND() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.SCF_PLG_INDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SCF_PLG_IND' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.SCF_PLG_INDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SCF_TY_REG() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.SCF_TY_REGColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SCF_TY_REG' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.SCF_TY_REGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VLG_REG_JR_BPL() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.VLG_REG_JR_BPLColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'VLG_REG_JR_BPL' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.VLG_REG_JR_BPLColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property JR_REG() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.JR_REGColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'JR_REG' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.JR_REGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TMS_OPS_REG() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.TMS_OPS_REGColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TMS_OPS_REG' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.TMS_OPS_REGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TMS_INC() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.TMS_INCColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TMS_INC' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.TMS_INCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PLA_INC() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.PLA_INCColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PLA_INC' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.PLA_INCColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DT_VZ_RAP_NW() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.DT_VZ_RAP_NWColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DT_VZ_RAP_NW' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.DT_VZ_RAP_NWColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DT_OK() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.DT_OKColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DT_OK' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.DT_OKColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DT_VZ_BST() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.DT_VZ_BSTColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DT_VZ_BST' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.DT_VZ_BSTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property OPM_OPS() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.OPM_OPSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'OPM_OPS' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.OPM_OPSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property OPM_CHEF_PO() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.OPM_CHEF_POColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'OPM_CHEF_PO' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.OPM_CHEF_POColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property OPM_HFD_BRW() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.OPM_HFD_BRWColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'OPM_HFD_BRW' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.OPM_HFD_BRWColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ID_OPS() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.ID_OPSColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ID_OPS' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.ID_OPSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DT_OPS_RAP_INTV() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.DT_OPS_RAP_INTVColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DT_OPS_RAP_INTV' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.DT_OPS_RAP_INTVColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SCF_REG() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.SCF_REGColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SCF_REG' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.SCF_REGColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SAP_SUPPLIER_ID() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.SAP_SUPPLIER_IDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SAP_SUPPLIER_ID' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.SAP_SUPPLIER_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DT_CHIP() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.DT_CHIPColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DT_CHIP' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.DT_CHIPColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property OPM_CHIP() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.OPM_CHIPColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'OPM_CHIP' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.OPM_CHIPColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CHIP_YN() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.CHIP_YNColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CHIP_YN' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.CHIP_YNColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VeraReference() As String
            Get
                If Me.IsVeraReferenceNull Then
                    Return String.Empty
                Else
                    Return CType(Me(Me.tableBBBEWREG.VeraReferenceColumn),String)
                End If
            End Get
            Set
                Me(Me.tableBBBEWREG.VeraReferenceColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VerslagContractantYN() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.VerslagContractantYNColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'VerslagContractantYN' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.VerslagContractantYNColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TMS_IKP_SENDMAIL() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.TMS_IKP_SENDMAILColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TMS_IKP_SENDMAIL' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.TMS_IKP_SENDMAILColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DateInvalid() As Date
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.DateInvalidColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DateInvalid' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.DateInvalidColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property UserInvalid() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.UserInvalidColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'UserInvalid' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.UserInvalidColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RemarkInvalid() As String
            Get
                Try 
                    Return CType(Me(Me.tableBBBEWREG.RemarkInvalidColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'RemarkInvalid' in table 'BBBEWREG' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBBBEWREG.RemarkInvalidColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsID_TY_REGNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.ID_TY_REGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetID_TY_REGNull()
            Me(Me.tableBBBEWREG.ID_TY_REGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsNM_INDNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.NM_INDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetNM_INDNull()
            Me(Me.tableBBBEWREG.NM_INDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVNM_INDNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.VNM_INDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVNM_INDNull()
            Me(Me.tableBBBEWREG.VNM_INDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSCF_PLG_INDNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.SCF_PLG_INDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSCF_PLG_INDNull()
            Me(Me.tableBBBEWREG.SCF_PLG_INDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSCF_TY_REGNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.SCF_TY_REGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSCF_TY_REGNull()
            Me(Me.tableBBBEWREG.SCF_TY_REGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVLG_REG_JR_BPLNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.VLG_REG_JR_BPLColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVLG_REG_JR_BPLNull()
            Me(Me.tableBBBEWREG.VLG_REG_JR_BPLColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsJR_REGNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.JR_REGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetJR_REGNull()
            Me(Me.tableBBBEWREG.JR_REGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTMS_OPS_REGNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.TMS_OPS_REGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTMS_OPS_REGNull()
            Me(Me.tableBBBEWREG.TMS_OPS_REGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTMS_INCNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.TMS_INCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTMS_INCNull()
            Me(Me.tableBBBEWREG.TMS_INCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPLA_INCNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.PLA_INCColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPLA_INCNull()
            Me(Me.tableBBBEWREG.PLA_INCColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDT_VZ_RAP_NWNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.DT_VZ_RAP_NWColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDT_VZ_RAP_NWNull()
            Me(Me.tableBBBEWREG.DT_VZ_RAP_NWColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDT_OKNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.DT_OKColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDT_OKNull()
            Me(Me.tableBBBEWREG.DT_OKColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDT_VZ_BSTNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.DT_VZ_BSTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDT_VZ_BSTNull()
            Me(Me.tableBBBEWREG.DT_VZ_BSTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsOPM_OPSNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.OPM_OPSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetOPM_OPSNull()
            Me(Me.tableBBBEWREG.OPM_OPSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsOPM_CHEF_PONull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.OPM_CHEF_POColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetOPM_CHEF_PONull()
            Me(Me.tableBBBEWREG.OPM_CHEF_POColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsOPM_HFD_BRWNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.OPM_HFD_BRWColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetOPM_HFD_BRWNull()
            Me(Me.tableBBBEWREG.OPM_HFD_BRWColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsID_OPSNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.ID_OPSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetID_OPSNull()
            Me(Me.tableBBBEWREG.ID_OPSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDT_OPS_RAP_INTVNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.DT_OPS_RAP_INTVColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDT_OPS_RAP_INTVNull()
            Me(Me.tableBBBEWREG.DT_OPS_RAP_INTVColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSCF_REGNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.SCF_REGColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSCF_REGNull()
            Me(Me.tableBBBEWREG.SCF_REGColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSAP_SUPPLIER_IDNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.SAP_SUPPLIER_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSAP_SUPPLIER_IDNull()
            Me(Me.tableBBBEWREG.SAP_SUPPLIER_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDT_CHIPNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.DT_CHIPColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDT_CHIPNull()
            Me(Me.tableBBBEWREG.DT_CHIPColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsOPM_CHIPNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.OPM_CHIPColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetOPM_CHIPNull()
            Me(Me.tableBBBEWREG.OPM_CHIPColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCHIP_YNNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.CHIP_YNColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCHIP_YNNull()
            Me(Me.tableBBBEWREG.CHIP_YNColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVeraReferenceNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.VeraReferenceColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVeraReferenceNull()
            Me(Me.tableBBBEWREG.VeraReferenceColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVerslagContractantYNNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.VerslagContractantYNColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVerslagContractantYNNull()
            Me(Me.tableBBBEWREG.VerslagContractantYNColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTMS_IKP_SENDMAILNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.TMS_IKP_SENDMAILColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTMS_IKP_SENDMAILNull()
            Me(Me.tableBBBEWREG.TMS_IKP_SENDMAILColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDateInvalidNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.DateInvalidColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDateInvalidNull()
            Me(Me.tableBBBEWREG.DateInvalidColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsUserInvalidNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.UserInvalidColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetUserInvalidNull()
            Me(Me.tableBBBEWREG.UserInvalidColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsRemarkInvalidNull() As Boolean
            Return Me.IsNull(Me.tableBBBEWREG.RemarkInvalidColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetRemarkInvalidNull()
            Me(Me.tableBBBEWREG.RemarkInvalidColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class BBBEWREGRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As BBBEWREGRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As BBBEWREGRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As BBBEWREGRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
