
CREATE PROC dbo.[USP_WY_BBDIEFDU_INSERT]
  @ID_DUP_DIEF varchar(30),
  @SCF_DUP char(10)=NULL,
  @INDI_NR_ST_VP bit=NULL,
  @INDI_NM_FRM_VP bit=NULL

AS
SET NOCOUNT OFF

INSERT INTO [BBDIEFDU] (
  [ID_DUP_DIEF],
  [SCF_DUP],
  [INDI_NR_ST_VP],
  [INDI_NM_FRM_VP]
)
VALUES (
  @ID_DUP_DIEF,
  @SCF_DUP,
  @INDI_NR_ST_VP,
  @INDI_NM_FRM_VP
)

