CREATE PROC dbo.[USP_WY_BBIND_UPDATEBESTEMMELING]
  @ID_IND int,
  @AD_EMAL_IND varchar(100)=NULL

AS
SET NOCOUNT OFF

UPDATE [BBIND] SET
  [AD_EMAL_IND] = @AD_EMAL_IND,
  [BST_IND] = 1
WHERE [ID_IND] = @ID_IND