
CREATE PROC dbo.[USP_WY_BBINTART_UPDATE]
  @ID_ART_INTV int,
  @ID_EH varchar(10)=NULL,
  @ID_GR_ART int=NULL,
  @SCF_ART_INTV varchar(50)=NULL,
  @PR_EH_ART_INTV float=NULL,
  @TSP_DU_INTV bit=NULL,
  @Original_ID_ART_INTV int --Primary Key Field

AS
SET NOCOUNT OFF

UPDATE [BBINTART] SET
  [ID_EH] = @ID_EH,
  [ID_GR_ART] = @ID_GR_ART,
  [SCF_ART_INTV] = @SCF_ART_INTV,
  [PR_EH_ART_INTV] = @PR_EH_ART_INTV,
  [TSP_DU_INTV] = @TSP_DU_INTV
WHERE [ID_ART_INTV] = @Original_ID_ART_INTV

