
-- Doel: Ophalen alle milieucoordinatoren
-- Auteur: dien mei2009

CREATE PROCEDURE [dbo].[USP_BBW_GET_ALL_BBAFDAMC]

AS

SET NOCOUNT OFF;

	SELECT BBAFDAMC.*, BBIND.AD_EMAL_IND as MAIL  FROM BBAFDAMC
	INNER JOIN BBIND
	ON BBIND.ID_IND = BBAFDAMC.ID_IND