
CREATE PROC dbo.[USP_WY_BBINBRINDTY_UPDATE]
  @ID_INBR_IND_TY int,
  @SCF_INBR_IND_TY varchar(50),
  @Original_ID_INBR_IND_TY int --Primary Key Field

AS
SET NOCOUNT OFF

UPDATE [BBINBRINDTY] SET
  [SCF_INBR_IND_TY] = @SCF_INBR_IND_TY
WHERE [ID_INBR_IND_TY] = @Original_ID_INBR_IND_TY

