-- Doel: Ophalen van alle milieuverontreinigingen bewaking
-- Auteur: dien mei 2009

CREATE    PROCEDURE [dbo].[USP_BBW_GET_ALL_milieuverontreinigingenBewaking]

AS

SET NOCOUNT OFF;
	select BBBEWREG.ID_REG, BBBEWREG.ID_TY_REG, 
		BBIND.NM_IND, BBIND.VNM_IND, BBBWPLG.SCF_PLG_IND, 
		BBREGTY.SCF_TY_REG,  
		BBBEWREG.VLG_REG_JR_BPL, year(BBBEWREG.TMS_OPS_REG) as JR_REG, 
		BBBEWREG.TMS_OPS_REG, BBBEWREG.TMS_INC, BBBEWREG.PLA_INC, 
		BBBEWREG.DT_VZ_RAP_NW, BBBEWREG.DT_OK, BBBEWREG.DT_VZ_BST, 
		BBBEWREG.OPM_OPS, 
		BBBEWREG.OPM_CHEF_PO, BBBEWREG.OPM_HFD_BRW,
		BBBEWREG.ID_OPS, BBBEWREG.DT_OPS_RAP_INTV, BBBEWREG.SCF_REG
	from BBBEWREG
	join BBREGTY on BBBEWREG.ID_TY_REG = BBREGTY.ID_TY_REG
	join BBBWPERS on BBBEWREG.ID_OPS = BBBWPERS.ID_IND
	join BBIND on BBBWPERS.ID_IND = BBIND.ID_IND
	join BBBWPLG on BBBWPERS.ID_PLG_IND = BBBWPLG.ID_PLG_IND
	where BBBEWREG.ID_TY_REG in (5, 9)
	order by BBBEWREG.TMS_OPS_REG