CREATE PROCEDURE [dbo].[USP_BBW_GET_ALL_InbreukReglementen]

AS

SET NOCOUNT OFF;

SELECT     BBINBRRG.ID_REG As RegistratieID, 
	     BBIND.NM_IND As Naam, BBIND.VNM_IND As Voornaam, BBIND.ID_IND As StamnrOvertreder,
	     BBINBRINDTY.SCF_INBR_IND_TY As OvertrederType, BBBEWREG.TMS_INC AS Tijdstip, MONTH(BBBEWREG.TMS_INC) 
                      AS Maand, YEAR(BBBEWREG.TMS_INC) AS Jaar, BBBEWREG.PLA_INC AS Plaats, BBINBRVA.SNL_OK AS ToegelatenSnelheid, BBINBRVA.SNL_REG AS GeregistreerdeSnelheid, 
                      BBINBRAR.NR_ART_INBR AS Artnr, BBINBRAR.SCF_ART_INBR AS Artikel, BBINBRTY.SCF_TY_INBR AS InbreukType, 
                      BBBEWREG.VLG_REG_JR_BPL As Volgnr
FROM         BBINBRRG INNER JOIN
                      BBINBRVA ON BBINBRRG.ID_REG = BBINBRVA.ID_REG INNER JOIN
                      BBINBRAR ON BBINBRVA.ID_ART_INBR = BBINBRAR.ID_ART_INBR INNER JOIN
                      BBINBRTY ON BBINBRAR.ID_TY_INBR = BBINBRTY.ID_TY_INBR INNER JOIN
                      BBBEWREG ON BBINBRRG.ID_REG = BBBEWREG.ID_REG INNER JOIN
                      BBIND ON BBINBRRG.ID_INBR = BBIND.ID_IND LEFT OUTER JOIN
                      BBINBRINDTY ON BBINBRRG.ID_INBR_IND_TY = BBINBRINDTY.ID_INBR_IND_TY
WHERE BBBEWREG.DateInvalid IS NULL                    
ORDER BY BBBEWREG.TMS_INC


