
CREATE PROC dbo.[USP_WY_BBINTVDU_UPDATE]
  @ID_DU_INTV int,
  @ID_INTV_BRDW int=NULL,
  @ID_ART_INTV int=NULL,
  @TYD_OPR datetime=NULL,
  @TYD_KO datetime=NULL,
  @TYD_END datetime=NULL,
  @Original_ID_DU_INTV int --Primary Key Field

AS
SET NOCOUNT OFF

UPDATE [BBINTVDU] SET
  [ID_INTV_BRDW] = @ID_INTV_BRDW,
  [ID_ART_INTV] = @ID_ART_INTV,
  [TYD_OPR] = @TYD_OPR,
  [TYD_KO] = @TYD_KO,
  [TYD_END] = @TYD_END
WHERE [ID_DU_INTV] = @Original_ID_DU_INTV

