CREATE PROC [dbo].[USP_WY_BBINTVBR_INSERT]
  @ID_INTV_BRDW int,
  @ID_TY_INTV int=NULL,
  @ID_BR_TY_INTV int=NULL,
  @ID_BR_RD_INTV int=NULL,
  @ID_AFD int=NULL,
  @ID_OPS int=NULL,
  @ID_CHEF_PO int=NULL,
  @ID_HFD_BRDW int=NULL,
  @ID_OK int=NULL,
  @IND_OPR_DR varchar(50)=NULL,
  @TMS_INTV datetime=NULL,
  @VLG_TY_INTV_JR int=NULL,
  @VLG_TY_INTV_AFD int=NULL,
  @PLA_INTV varchar(1000)=NULL,
  @ID_OK_VU_TK varchar(50)=NULL,
  @SCF_LNG_INTV varchar(8000)=NULL,
  @INDI_BRD_BLUS_AFD bit=NULL,
  @INDI_BRD_BLUS_SID bit=NULL,
  @INDI_BRDW_SID_OPR bit=NULL,
  @INDI_RAP_INC_OTV bit=NULL,
  @DT_OPS_RAP_INTV datetime=NULL,
  @DT_VZ_RAP_NW datetime=NULL,
  @DT_OK datetime=NULL,
  @DT_VZ_BST datetime=NULL,
  @OPM_OPS varchar(100)=NULL,
  @OPM_CHEF_PO varchar(100)=NULL,
  @OPM_HFD_BRW varchar(100)=NULL,
  @BST_OUD_PG varchar(300)=NULL,
  @VeraLink Varchar(500)=NULL, -- VRST 11/03/2012
  @VeraReference Varchar(100)= NULL,  -- VRST 11/03/2012
  @VerslagContractantYN bit -- VRST 11/03/2013

AS
SET NOCOUNT OFF

INSERT INTO [BBINTVBR] (
  [ID_INTV_BRDW],
  [ID_TY_INTV],
  [ID_BR_TY_INTV],
  [ID_BR_RD_INTV],
  [ID_AFD],
  [ID_OPS],
  [ID_CHEF_PO],
  [ID_HFD_BRDW],
  [ID_OK],
  [IND_OPR_DR],
  [TMS_INTV],
  [VLG_TY_INTV_JR],
  [VLG_TY_INTV_AFD],
  [PLA_INTV],
  [ID_OK_VU_TK],
  [SCF_LNG_INTV],
  [INDI_BRD_BLUS_AFD],
  [INDI_BRD_BLUS_SID],
  [INDI_BRDW_SID_OPR],
  [INDI_RAP_INC_OTV],
  [DT_OPS_RAP_INTV],
  [DT_VZ_RAP_NW],
  [DT_OK],
  [DT_VZ_BST],
  [OPM_OPS],
  [OPM_CHEF_PO],
  [OPM_HFD_BRW],
  [BST_OUD_PG],
  [VeraReference],
  [VeraLink],
  [VerslagContractantYN]
)
VALUES (
  @ID_INTV_BRDW,
  @ID_TY_INTV,
  @ID_BR_TY_INTV,
  @ID_BR_RD_INTV,
  @ID_AFD,
  @ID_OPS,
  @ID_CHEF_PO,
  @ID_HFD_BRDW,
  @ID_OK,
  @IND_OPR_DR,
  @TMS_INTV,
  @VLG_TY_INTV_JR,
  @VLG_TY_INTV_AFD,
  @PLA_INTV,
  @ID_OK_VU_TK,
  @SCF_LNG_INTV,
  @INDI_BRD_BLUS_AFD,
  @INDI_BRD_BLUS_SID,
  @INDI_BRDW_SID_OPR,
  @INDI_RAP_INC_OTV,
  @DT_OPS_RAP_INTV,
  @DT_VZ_RAP_NW,
  @DT_OK,
  @DT_VZ_BST,
  @OPM_OPS,
  @OPM_CHEF_PO,
  @OPM_HFD_BRW,
  @BST_OUD_PG,
  @VeraLink,
  @VeraReference,
  @VerslagContractantYN
)