
-- Doel: Ophalen alle  dagverslagen inlichtingen
-- Auteur: SIDDIEN okt 2006

CREATE PROCEDURE [dbo].[USP_BBW_GET_ALL_BBDGPO]
 @datumVanaf datetime,
 @datumTot datetime
AS

SET NOCOUNT OFF;


SELECT 
	BBDGPO.ID_DG_PO, 
	BBDGPO.ID_DG_PO_DL,
	BBDGPO.TMS_REG_DG_PO,
	BBDGPO.Q_PO_1,
	BBDGPO.Q_PO_2,
	BBDGPO.Q_PO_4,
	BBDGPO.Q_PO_ALG,
	DATEPART(yyyy, BBDGPO.TMS_REG_DG_PO) as Jaar,
	DATEPART(mm, BBDGPO.TMS_REG_DG_PO) as Maand,
	DATEPART(wk, BBDGPO.TMS_REG_DG_PO) as WeekNr,
	BBDGPODL.INV_PO,
	BBDGPODL.VLG
FROM BBDGPO
INNER JOIN BBDGPODL
ON BBDGPODL.ID_DG_PO_DL = BBDGPO.ID_DG_PO_DL
WHERE BBDGPO.TMS_REG_DG_PO >= @datumVanaf
AND BBDGPO.TMS_REG_DG_PO <= @datumTot
ORDER BY BBDGPODL.VLG ASC

