
CREATE PROC dbo.[USP_WY_BBOPKAST_UPDATE]
  @ID_REG int,
  @ID_TITU_KAST int,
  @ID_AFD int,
  @ID_DNS_OPS_KAST_VR int,
  @ID_OTV_EIG_SID int,
  @ID_OTV_EIG_TITU int,
  @SCF_RD_OPN_KAST varchar(3000),
  @SCF_EIG_SID varchar(1000),
  @SCF_EIG_TITU varchar(1000),
  @INF_EX_OPN_KAST varchar(1000),
  @Original_ID_REG int --Primary Key Field

AS
SET NOCOUNT OFF

UPDATE [BBOPKAST] SET
  [ID_TITU_KAST] = @ID_TITU_KAST,
  [ID_AFD] = @ID_AFD,
  [ID_DNS_OPS_KAST_VR] = @ID_DNS_OPS_KAST_VR,
  [ID_OTV_EIG_SID] = @ID_OTV_EIG_SID,
  [ID_OTV_EIG_TITU] = @ID_OTV_EIG_TITU,
  [SCF_RD_OPN_KAST] = @SCF_RD_OPN_KAST,
  [SCF_EIG_SID] = @SCF_EIG_SID,
  [SCF_EIG_TITU] = @SCF_EIG_TITU,
  [INF_EX_OPN_KAST] = @INF_EX_OPN_KAST
WHERE [ID_REG] = @Original_ID_REG

