CREATE   PROCEDURE [dbo].[USP_BBW_GET_ALL_BBBEWREG]

AS

SET NOCOUNT OFF;		
	select BBBEWREG.ID_REG, BBBEWREG.ID_TY_REG, 
		BBIND.NM_IND, BBIND.VNM_IND, BBBWPLG.SCF_PLG_IND, 
		BBREGTY.SCF_TY_REG,  
		BBBEWREG.VLG_REG_JR_BPL, year(BBBEWREG.TMS_OPS_REG) as JR_REG, 
		BBBEWREG.TMS_OPS_REG, BBBEWREG.TMS_INC, BBBEWREG.PLA_INC, 
		BBBEWREG.DT_VZ_RAP_NW, BBBEWREG.DT_OK, BBBEWREG.DT_VZ_BST, 
		BBBEWREG.OPM_OPS, 
		BBBEWREG.OPM_CHEF_PO, BBBEWREG.OPM_HFD_BRW,
		BBBEWREG.ID_OPS, BBBEWREG.DT_OPS_RAP_INTV, BBBEWREG.SCF_REG,
		--Add CHIP columns - Lawrence Verbruggen - 04/03/2011
		BBBEWREG.SAP_SUPPLIER_ID, BBBEWREG.DT_CHIP , BBBEWREG.OPM_CHIP , 
		CAST(CASE WHEN BBBEWREG.CHIP_YN IS NULL THEN 0 ELSE BBBEWREG.CHIP_YN END As Bit) AS CHIP_YN,
		--Add Vera columns - SIDVRST 12/03/2013
		BBBEWREG.VeraReference,  BBBEWREG.VerslagContractantYN,
		--Add TMS_IKP_SENDMAIl
		BBBEWREG.TMS_IKP_SENDMAIL,
		BBBEWREG.DateInvalid,
		BBBEWREG.UserInvalid,
		BBBEWREG.RemarkInvalid
	from BBBEWREG
	join BBREGTY on BBBEWREG.ID_TY_REG = BBREGTY.ID_TY_REG
	join BBBWPERS on BBBEWREG.ID_OPS = BBBWPERS.ID_IND
	join BBIND on BBBWPERS.ID_IND = BBIND.ID_IND
	join BBBWPLG on BBBWPERS.ID_PLG_IND = BBBWPLG.ID_PLG_IND
	order by BBBEWREG.TMS_OPS_REG
