
CREATE PROC dbo.[USP_WY_BBVZKFRM_INSERT]
  @ID_FRM_VZK int,
  @NM_FRM_VZK varchar(100)=NULL,
  @AD_FRM_VZK varchar(200)=NULL,
  @PLA_FRM_VZK varchar(100)=NULL

AS
SET NOCOUNT OFF

INSERT INTO [BBVZKFRM] (
  [ID_FRM_VZK],
  [NM_FRM_VZK],
  [AD_FRM_VZK],
  [PLA_FRM_VZK]
)
VALUES (
  @ID_FRM_VZK,
  @NM_FRM_VZK,
  @AD_FRM_VZK,
  @PLA_FRM_VZK
)

