SET IDENTITY_INSERT [dbo].[bmSoortTypeMateriaal] ON
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (1, 1, 1, 1, N'poederapp. 1 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (2, 1, 1, 3, N'poederapp. 3 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (3, 1, 1, 6, N'poederapp. Turex 6 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (4, 1, 1, 6, N'poederapp. 7006')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (5, 1, 1, 6, N'poederapp. 8006')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (6, 1, 1, 6, N'poederapp. Sicli 6 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (7, 1, 1, 6, N'poederapp. BGS 6 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (8, 1, 1, 7, N'poederapp Ansul 7 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (9, 1, 1, 12, N'poederapp. Turex 12 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (10, 1, 1, 12, N'poederapp. 7012')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (11, 1, 1, 12, N'poederapp. 8012')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (12, 1, 1, 12, N'poederapp. Sicli 12 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (13, 1, 1, 12, N'poederapp. BGS 12 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (14, 1, 1, 50, N'poederapp. Turex 50 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (15, 1, 1, 50, N'poederapp. Ansul PR 50')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (16, 1, 1, 50, N'poederapp Ansul  7050')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (17, 1, 2, 2, N'-')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (18, 1, 2, 5, N'CO2 toestel BGS 5 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (19, 1, 2, 5, N'CO2 toestel Saval 5 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (20, 1, 2, 5, N'CO2 toestel Sicli 5 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (21, 1, 2, 2, N'BCF toestel Ansul 1,5 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (22, 1, 2, 6, N'BCF toestel Ansul 6 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (23, 1, 2, 7, N'BCF toestel Saval 7 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (24, 1, 2, 5, N'CO2 toestel Ansul 5 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (27, 1, 2, 5, N'CO2 toestel TUREX 5 kg.')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (28, 1, 1, 7, N'poederapp. A 20 E Ansul')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (29, 1, 1, 50, N'poederapp.BGS 50kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (30, 1, 2, 50, N'drukfles P50')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (31, 1, 4, 5, N'CO2 DRUKFLES')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (32, 1, 3, 5, N'N2 DRUKFLES')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (33, 1, 5, 6, N'schuimblustoestel 6 liter')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (34, 1, 5, 9, N'schuimblustoestel 9 liter')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (35, 1, 4, 30, N'CO2 toestel BGS 30 kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (36, 1, 4, 2, N'CO2 toestel BGS 2kg')
INSERT INTO [dbo].[bmSoortTypeMateriaal] ([SoortTypeMatID], [TypeMatID], [BrandblusCodeID], [BrandblusInhoud], [SoortTypeMatOmschr]) VALUES (37, 1, 4, 2, N'CO2 toestel Ansul 2kg')
SET IDENTITY_INSERT [dbo].[bmSoortTypeMateriaal] OFF