SET IDENTITY_INSERT [dbo].[bmLeverancier] ON
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (1, N'ANSUL')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (2, N'SICLI')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (3, N'BGS')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (4, N'TUREX')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (5, N'SAVAL')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (6, N'vervangen in 2006')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (7, N'nieuw geplaatst in 99')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (8, N'nieuw geplaatst in 2006')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (9, N'vervangen in 2000')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (10, N'SOMATI')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (11, N'vervangen in 2011')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (12, N'VANRULLEN')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (13, N'vervangen in 2001')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (14, N'nieuw geplaatst in 2001')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (15, N'nieuw geplaatst in 2002')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (16, N'vervangen in 2002')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (17, N'nieuw geplaatst in 2003')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (18, N'vervangen in 2003')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (19, N'nieuw geplaatst in 2004')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (20, N'vervangen in 2004')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (21, N'nieuw geplaatst in 2005')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (22, N'vervangen in 2005')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (23, N'nieuw geplaatst in 2007')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (24, N'vervangen in 2007')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (25, N'nieuw geplaatst in 2008')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (26, N'vervangen in 2008')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (27, N'nieuw geplaatst in 2009')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (28, N'vervangen in 2009')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (29, N'nieuw geplaatst in 2010')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (30, N'vervangen in 2010')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (31, N'nieuw geplaatst in 2011')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (32, N'Wasterlain')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (33, N'nieuw geplaatst in 2012')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (34, N'vervangen in 2012')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (35, N'vervangen 2012  afgekeurd')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (36, N'nieuw geplaatst in 2013')
INSERT INTO [dbo].[bmLeverancier] ([LeverancierID], [NaamLeverancier]) VALUES (37, N'vervangen in 2013')
SET IDENTITY_INSERT [dbo].[bmLeverancier] OFF