INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (1, N'000')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND],[PLG_Mail]) VALUES (2, N'060','SIDADHT@arcelormittal.onmicrosoft.com;arnedho@hotmail.com')
--INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND],[PLG_Mail]) VALUES (2, N'060','steven.desmaele@arcelormittal.com;peter.bosschaerts@arcelormittal.com')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND],[PLG_Mail]) VALUES (3, N'061','luc.r.haenebalcke@arcelormittal.com;chris.vandoorslaer@arcelormittal.com' )
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND],[PLG_Mail]) VALUES (4, N'062','Marnix.debbaut@arcelormittal.com;sylvain.vantheemssche@arcelormittal.com')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND],[PLG_Mail]) VALUES (5, N'063','')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND],[PLG_Mail]) VALUES (6, N'064','')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (7, N'bew')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (8, N'A')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (9, N'B')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (10, N'C')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (11, N'D')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (12, N'A 737462')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (13, N'A875806')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (14, N'CobelGuard')
INSERT INTO [dbo].[BBBWPLG] ([ID_PLG_IND], [SCF_PLG_IND]) VALUES (15, N'Securitas')
