SET IDENTITY_INSERT [dbo].[bmAfdeling] ON
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (1, N'DD', N'Diverse Diensten')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (3, N'GLT', N'Galtec')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (5, N'AD', N'Algemene Diensten')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (6, N'KWA', N'Koudwalserij')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (7, N'RBV', N'Grondstoffen,Haven,Vervoer & Recup.')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (9, N'HOO', N'Hoogovens')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (12, N'WWA', N'Warmwalserij')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (13, N'COO', N'Cokesfabriek')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (14, N'STL', N'Staalfabriek')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (16, N'KBH', N'Kwaliteitsbeheer')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (17, N'BRA mag', N'Magazijn')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (18, N'BRA', N'Brandweer')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (19, N'SID', N'Sidmarterrein')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (20, N'LPK', N'Loopkranen')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (21, N'GHV', N'Grondstoffen,Haven en vervoer')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (22, N'AFGEK99', N'Afgekeurde toestellen')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (23, N'VERDW', N'Verdwenen toestellen')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (24, N'EXO', N'Externe ondernemingen')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (25, N'VERV 2000', N'Vervangen toestel 2004')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (26, N'VERDW 2006', N'Verdwenen toestel 2006')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (27, N'SGL', N'Sidgal 2, 3 en 4')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (28, N'TBG', N'Tailored Blank Gent')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (29, N'VERDW 2001', N'VERDWENEN 2001')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (30, N'verv 2006', N'VERVANGEN TOESTEL 2006')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (32, N'VERVN 2002', N'Vervangen toestel 2002')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (34, N'VERDW 2002', N'VERDWENEN TOESTEL 2002')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (35, N'DECO', N'DECOSTEEL')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (36, N'VERV 2003', N'VERVANGEN TOESTEL 2003')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (37, N'VERDW 2003', N'VERDWENEN TOESTEL 2003')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (43, N'Verdw2005', N'Verdwenen toestel 2005')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (44, N'Verv2005', N'Vervangen toestel 2005')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (46, N'OCAS', N'OCAS')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (47, N'VERV 2007', N'VERVANGEN TOESTEL 2007')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (48, N'VERV 2008', N'Vervangen in 2008')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (49, N'VERV 2009', N'VERVANGEN TOESTEL 2009')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (50, N'VERDW 2009', N'VERDWENEN TOESTEL 2009')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (51, N'VERV 2010', N'VERVANGEN TOESTEL 2010')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (52, N'VERDW 2010', N'VERDWENEN TOESTEL 2010')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (53, N'AFGEK 2012', N'Afgekeurde toestellen 2012')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (54, N'VERDW 2012', N'Verdwenen toestellen 2012')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (55, N'VERV 2012', N'Vervangen toestellen 2012')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (56, N'OCAS Zw', N'Ocas Zwijnaarde')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (57, N'VERDW 2013', N'Verdwenen toestellen 2013')
INSERT INTO [dbo].[bmAfdeling] ([AfdelingID], [AfdelingCode], [AfdelingNaam]) VALUES (58, N'VERV 2013', N'Vervangen toestellen 2013')
SET IDENTITY_INSERT [dbo].[bmAfdeling] OFF
